### ISSUE TITLE
tss_items_worked is missing

### ISSUE THREAD

**Issue by mistydemeo** [suppertails66/wdtools#2]
Commit 54e076ce369d06cddfa4b65f573f973eb99bdeb4 added `tss_items_worked` to the makefile, but it looks like the source got missed.

**Comment by suppertails66** [comment]
Oh, that shouldn't have been in there in the first place -- removed. It was a slightly modified version of items_tss that I used to make a joke hack that made TSS absurdly difficult, nothing actually useful.
